class EnglishLocale {
  static const EN = {
    "stores": "Store List",
    "/stores": "Store List",
    "home": "Home",
    "StoreList": "Store List",
    "storeAccount": "Store Account",
    "ApprovedList": "Approved List",
    "AcquiredList": 'Acquired List',
    "SettlementList": 'Settlement List',
    "SettlementDetailList": 'Settlement Detail List',
    "TransferList": 'Transfer List',
    "detail": "Detail",
    'copyright': 'Copyright © 2020 ibexlab.\nAll Rights Reserved.',
    "payment_info": "Payment info",
    "transactions": 'Transactions',
    "approved_list": 'Approved List',
    "/approved": 'Approved List',
    "acquired_list": 'Acquired List',
    "/acquired": 'Acquired List',
    "settlement": 'Settlement',
    "settlement_list": 'Settlement List',
    "/settlements": 'Settlement List',
    "settlement_detail_list": 'Settlement Detail List',
    "/settlementdetails": 'Settlement Detail List',
    "transfer_list": 'Transfer List',
    "/transfers": 'Transfer List',
    "Home": 'Transfer List',
    "business": 'Business',
    'businessRegistrationNo': 'BIN/INN',
    'paymentMethodCode': 'Payment Method Code',
    'paymentMethodName': 'Payment Method Name',
    'approvalDatetime': 'Approved Date',
    'transactionType': 'TxType',
    'acquirerName': 'Acquirer',
    'cardNo': 'Card No',
    'approvalAmount': 'Amount',
    'approvalNo': 'Approve No',
    'resultCode': 'Res.Code',
    "header": 'header',
    "id": "ID",
    "enter_id": "Enter ID",
    "password": "Password",
    "enter_password": "Enter password",
    "login": "Login",
    "sign_up": "Sign up",
    "find_id": "Find ID",
    "reset_password": "Reset Password",
    "password_must_be_more_than_6_charater":
        "Password must be more than 6 charater",
    "id_must_be_more_than_6_charater": "ID must be more than 6 charater",
    "domain_must_be_selected": "Domain must be selected",
    "domain": "Domain",
    "table": "Table",
    "new_store": "New Store",
    "remove_store": "Remove Store",
    "basic_info": "Basic info",
    "account_info": "Account info",
    "back": "Back",
    "save": "Save",
    "refresh_page": "Refresh Page",
    "payment_method": "Payment Method",
    "card_ksnet_pg": "[CARD]KSNET_PG",
    "transaction_fee": "Transaction fee",
    "the_commission_rate_applied_to_the_store":
        "The commission rate applied to the store",
    "tid": "TID",
    "terminal_id": "Terminal ID",
    "settlement_account": "Settlement Account",
    "owner_name": "Owner Name",
    "required": "Required",
    "bin_inn": "BIN/INN",
    "license": "License",
    "login_id": "Login ID",
    "phone_no": "Phone No.",
    "address": "Address",
    "name": "Name",
    "alias_​​displayed_on_screen": "Alias displayed on screen",
    "transfer_module": "Transfer Module",
    "deposit_bank": "Deposit Bank",
    "account_no": "Account No",
    "enter_the_deposit_account_number": "Enter the deposit account number.",
    "holder_name": "Account holder name",
    "please_enter_the_name_of_the_account_holder":
        "Please enter the name of the account holder.",
    "go_to_login": "Go to login",
    "download_excel": "Download excel",
    "all": "All",
    "store_name": "Store Name",
    "creation_date": "Creation Date",
    "inquiry_filter": "Inquiry Filter",
    "close": "Close",
    "search": "Search",
    "from_approved_date": "From-(Approved Date)",
    "to_approved_date": "To-(Approved Date)",
    "transaction_id": "Transaction ID",
    "order_id": "Order ID",
    "tx_type": "TxType",
    "approved_no": "Approved No.",
    "amount": "Amount",
    "field_must_be_numeric_only": "Field must be numeric only",
    "store_information": "Store information",
    "state": "State",
    "add": "Add",
    "details": "Details",
    "today": "Today",
    "dec_2020": "Dec 2020",
    "mo": "Mo",
    "tu": "Tu",
    "we": "We",
    "th": "Th",
    "fr": "Fr",
    "sa": "Sa",
    "su": "Su",
    "are_you_sure_to_remove_this_store":
        "Are you sure to remove this store? This\naction cannot be undone",
    "cancel": "Cancel",
    "remove": "Remove",
    "tab": "Tab",
    "total_count": "Total Count",
    "total_approved_amount": "Total Approved Amount",
    "horizontal_scroll_from_table_scroller":
        "Horizontal Scroll from Table scroller!",
    "previous": "Previous",
    "next": "Next",
    "show": "Show",
    "good_morning": "Good morning",
    "dismiss": "Dismiss",
    "reset_the_cart": "Reset the cart",
    "reset_cart_warning": "Reset cart warning",
    "loading_please_wait": "Loading, please wait!",
    "download": "Download",
    "upload": "Upload",
    "storeName": "Store Name",
    "loginId": "Login",
    "creationTime": "Creation Date",
    "primaryAddress": "Address",
    "acquirementState": "State",
    "requestDatetime": "Request Date",
    "completeDatetime": "Done Date",
    "settlementId": "Settlement ID",
    "settlementDatetime": "Settlement Date",
    "expectedTransferDate": "Expected Date",
    "transferDate": "Transfer Date",
    "transactionCount": "Count",
    "settlementAmount": "Amount",
    "settlementFee": "Commission",
    "settlementTax": "Tax",
    "depositAmount": "Transfer Amt.",
    "transferMethod": "Settlement Method",
    "transactionId": "Transaction ID",
    "orderId": "Order ID",
    "transferId": "Transfer ID",
    "KZT": "KZT",
    "approved_information": "Approved Information",
    "amount_information": "Amount Information",
    "detail_info": "Detail Information",
    "acquirerCode": "Acquirer Code",
    "transferMethodCode": "Transfer Method Code",
    "transferMethodName": "Transfer Method Name",
    "expectedTransferDatetime": "Expected Transfer Date",
    "transferDatetime": "Transfer Date",
    "transferState": "Transfer State",
    "depositBankName": "Deposit Bank Name",
    "depositAccountNo": "Deposit Account No",
    "updateDatetime": "Update Date",
    "select_payment_module": "Select payment module",
    "other_inputs": "Other Inputs",
    "withdrawal_account": "Withdrawal Account",
    "receiving_info": "Receiving Info",
    "state_history": "State History",
    "transferResult": "Result",
    "comment": "Comment",
    "alias_displayed_on_screen": "Alias displayed on screen",
    "depositer_acc_no": "Enter the deposit account number",
    "acc_holder_name": "Please enter the name of the account holder",
    "password_must_be_more_than_6_character":
        'Password must be more than 6 characters!',
    "id_must_be_more_than_6_character": 'ID must be more than 6 characters!',
    "ApprovedDetail": 'Approved Details',
    "StoreDetail-Basic": 'Store Basic Details',
    "StoreDetail-Payment": 'Store Payment Details ',
    "StoreDetail-Account": 'Store Account Details',
    "TransferDetail": 'Transfer Details',
    "select_transfer_module": "Please select transfer module!",
    "select_deposit_bank": "Please select deposit bank!",
    "select_payment_method": "Please select payment method!",
    "primary_address": "Primary Address",
    "detail_address": "Detail Address",
  };
}
