/// Flutter icons AntIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AntIcon
///      fonts:
///       - asset: fonts/AntIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AntIcon {
  AntIcon._();

  static const _kFontFam = 'AntIcon';
  static const String? _kFontPkg = null;

  static const IconData StepBackward = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ArrowsAlt = IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Backward = IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData CaretDown = IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData CaretLeft = IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData CaretRight = IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData CaretUp = IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData DoubleLeft = IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData DoubleRight = IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Down = IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData DownCircle = IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Enter = IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData FastBackward = IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData FastForward = IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Forward = IconData(0xe90e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Left = IconData(0xe90f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData LeftCircle = IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Retweet = IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Right = IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData RightCircle = IconData(0xe913, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Rollback = IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Shrink = IconData(0xe915, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData step_forward = IconData(0xe916, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Up = IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData UpCircle = IconData(0xe918, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData VerticalAlignBottom = IconData(0xe919, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData VerticalAlignMiddle = IconData(0xe91a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData VerticalAlignTop = IconData(0xe91b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData VerticalLeft = IconData(0xe91c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData VerticalRight = IconData(0xe91d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
